version: "3"
services:
  a-spider:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672