version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
  # a-spider:
  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
